# Default configuration for Crypto Foresight

# Model Configuration
model:
  # Forecasting horizon in days
  horizon: 7
  
  # Prophet-specific parameters
  prophet:
    seasonality_mode: 'multiplicative'
    changepoint_prior_scale: 0.05
    seasonality_prior_scale: 10.0
    holidays_prior_scale: 10.0
    n_iter: 1000
    
    # Seasonality settings
    yearly_seasonality: true
    weekly_seasonality: true
    daily_seasonality: false
    
  # Feature engineering
  features:
    # Technical indicators
    include_sma: true
    sma_windows: [7, 14, 30]
    include_ema: true
    ema_windows: [12, 26]
    include_rsi: true
    rsi_period: 14
    include_macd: true
    
    # Price-based features
    include_returns: true
    return_periods: [1, 3, 7]
    include_volatility: true
    volatility_window: 30

# Service Configuration
service:
  # API settings
  host: "0.0.0.0"
  port: 8000
  debug: true
  
  # CORS settings
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
  
  # WebSocket settings
  ws_heartbeat_interval: 30
  
  # Market data settings
  market_data:
    provider: "coingecko"
    cache_ttl: 300  # seconds
    retry_attempts: 3
    retry_delay: 1  # seconds
    
  # Supported symbols
  supported_symbols:
    - "bitcoin"
    - "ethereum" 
    - "solana"
    - "cardano"
    - "polkadot"
    - "chainlink"
  
  # Model artifacts
  artifacts_path: "./artifacts"
  
# Training Configuration
training:
  # Data requirements
  min_data_points: 100
  train_test_split: 0.8
  
  # Validation
  cross_validation:
    enabled: true
    initial: "730 days"  # Initial training period
    period: "180 days"   # Spacing between cutoff dates
    horizon: "30 days"   # Forecast horizon for validation
  
  # Model persistence
  save_model: true
  model_format: "pickle"
  include_metadata: true
