# Development overrides for Crypto Foresight

# Model Configuration (dev-specific)
model:
  horizon: 3  # Shorter horizon for faster development
  
  prophet:
    n_iter: 500  # Fewer iterations for faster training
    
  features:
    # Simplified features for development
    sma_windows: [7, 14]
    ema_windows: [12, 26]
    return_periods: [1, 3]

# Service Configuration (dev-specific)
service:
  debug: true
  
  market_data:
    cache_ttl: 60  # Shorter cache for development
    
  # Additional dev symbols for testing
  supported_symbols:
    - "bitcoin"
    - "ethereum"
    - "solana"
    - "dogecoin"  # Additional for testing

# Training Configuration (dev-specific)
training:
  min_data_points: 30  # Lower requirement for testing
  
  cross_validation:
    enabled: false  # Disable CV in development for speed
    
# Logging Configuration (dev-specific)
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - console
  
# Development-specific features
dev:
  # Mock data when external APIs are unavailable
  use_mock_data: false
  
  # Hot-reloading
  auto_reload: true
  
  # Debugging
  enable_profiling: false
